/* Optional real-browser checks. npm test stays dependency-free.
 * node tests/browser-check.mjs --module=/path/to/playwright/index.mjs --url=http://127.0.0.1:4191
 */
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const options = Object.fromEntries(process.argv.slice(2).map((arg) => arg.replace(/^--/, '').split('=')));
const { chromium } = await import(options.module || 'playwright');
const base = options.url || 'http://127.0.0.1:4173';
const phase = options.phase || 'review';
const output = options.output || join(tmpdir(), 'systems-craft');
await mkdir(output, { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = [];
const requests = [];
page.on('request', (request) => requests.push(request.url()));
page.on('response', (response) => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
page.on('pageerror', (error) => errors.push(error.message));
try {
  await page.goto(base);
  await page.waitForFunction(() => document.querySelector('#opening-diagram').dataset.stage === '3');
  await page.evaluate(() => document.fonts.ready);
  await page.waitForFunction(() => !document.getAnimations().some((animation) => document.querySelector('#opening-diagram').contains(animation.effect.target)));
  await page.screenshot({ path: `${output}/${phase}-desktop.png` });
  await page.locator('#diagram-replay').click();
  assert.equal(await page.locator('#opening-diagram').getAttribute('data-stage'), '0');
  await page.waitForFunction(() => document.querySelector('#opening-diagram').dataset.stage === '3');
  await page.locator('#reservoir-step').click();
  assert.equal(await page.locator('#stock-value').textContent(), '52');
  await page.locator('#inflow').fill('12');
  await page.locator('#outflow').fill('0');
  for (let i = 0; i < 5; i++) await page.locator('#reservoir-step').click();
  assert.equal(await page.locator('#stock-value').textContent(), '100');
  assert.match(await page.locator('#reservoir-status').textContent(), /spills over/);
  await page.locator('#inflow').fill('0');
  await page.locator('#outflow').fill('12');
  for (let i = 0; i < 9; i++) await page.locator('#reservoir-step').click();
  assert.equal(await page.locator('#stock-value').textContent(), '0');
  await page.locator('#reservoir-reset').click();
  assert.equal(await page.locator('#stock-value').textContent(), '50');
  await page.locator('#reservoir-toggle').click();
  await page.waitForFunction(() => Number(document.querySelector('#reservoir-time').textContent) >= 1);
  await page.locator('#feedback').scrollIntoViewIfNeeded();
  await page.waitForFunction(() => document.querySelector('#reservoir-toggle').getAttribute('aria-pressed') === 'false');
  await page.locator('#reservoir-reset').click();
  await page.locator('#stocks').screenshot({ path: `${output}/${phase}-stocks.png` });
  const growth = await page.locator('#feedback-path').getAttribute('d');
  await page.locator('[data-feedback=balancing]').click();
  assert.equal(await page.locator('#loop-letter').textContent(), 'B');
  assert.notEqual(await page.locator('#feedback-path').getAttribute('d'), growth);
  await page.locator('#delay').fill('10');
  assert.match(await page.locator('#delay-status').textContent(), /overshoots/);
  await page.locator('#delays').screenshot({ path: `${output}/${phase}-delays.png` });
  await page.locator('[data-stress="2"]').click();
  assert.match(await page.locator('#resilience-status').textContent(), /10 hours/);
  await page.waitForFunction(() => !document.getAnimations().some((animation) => document.querySelector('#resilience').contains(animation.effect.target)));
  await page.locator('#resilience').screenshot({ path: `${output}/${phase}-resilience.png` });
  await page.locator('#pattern').fill('The queue doubles every Friday.');
  await page.locator('#sheet-next').click();
  assert.equal(await page.locator('#accumulation').isVisible(), true);
  assert.equal(await page.locator('#pattern').isVisible(), false);
  await page.locator('#accumulation').fill('Unfinished requests.');
  await page.locator('#sheet-next').click();
  await page.locator('#connections').fill('Rushing causes rework.');
  await page.locator('#sheet-next').click();
  await page.locator('#experiment').fill('Limit new requests. Review in two weeks.');
  await page.locator('#sheet-next').click();
  assert.equal(await page.locator('#field-sheet').getAttribute('data-stage'), '4');
  assert.equal(await page.locator('#pattern').isVisible(), true);
  await page.waitForFunction(() => document.querySelector('#sheet-status').textContent.includes('Saved'));
  await page.locator('#field-sheet').screenshot({ path: `${output}/${phase}-worksheet.png` });
  await page.reload();
  assert.equal(await page.locator('#pattern').inputValue(), 'The queue doubles every Friday.');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#download-sheet').click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(), 'systems-field-notes.txt');
  // Print only the field sheet through the same entry point as the reader.
  await page.evaluate(() => { window.print = () => dispatchEvent(new Event('beforeprint')); });
  await page.locator('#print-sheet').click();
  await page.emulateMedia({ media: 'print' });
  assert.equal(await page.locator('#print-notes p').count(), 4);
  assert.match(await page.locator('#print-notes').textContent(), /The queue doubles every Friday/);
  assert.equal(await page.locator('#stocks').isVisible(), false);
  assert.equal(await page.locator('#practice').isVisible(), true);
  assert.equal(await page.locator('details:not([open])').count(), 0);
  await page.setViewportSize({ width: 794, height: 1123 });
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({ path: `${output}/${phase}-print.png`, fullPage: true });
  await page.evaluate(() => dispatchEvent(new Event('afterprint')));
  assert.equal(await page.locator('details[open]').count(), 0);
  assert.equal(await page.locator('.ladder-row[name=leverage]').count(), 12);
  await page.emulateMedia({ media: 'screen' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('.ladder-row').first().locator('summary').focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('.ladder-row').first().getAttribute('open'), '');
  await page.locator('.ladder-row').nth(1).locator('summary').click();
  assert.equal(await page.locator('.ladder-row').first().getAttribute('open'), null);
  await page.locator('.trap-card').first().locator('summary').focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('.trap-card').first().getAttribute('open'), '');
  const structure = await page.evaluate(() => {
    const ids = [...document.querySelectorAll('[id]')].map((el) => el.id);
    return { duplicates: ids.filter((id, i) => ids.indexOf(id) !== i), broken: [...document.querySelectorAll('a[href^="#"]')].map((link) => link.hash.slice(1)).filter((id) => !document.getElementById(id)) };
  });
  assert.deepEqual(structure, { duplicates: [], broken: [] });
  for (const width of [1440, 1024, 800, 768, 560, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}`);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base);
  await page.waitForFunction(() => document.querySelector('#opening-diagram').dataset.stage === '3');
  await page.evaluate(() => document.fonts.ready);
  await page.waitForFunction(() => !document.getAnimations().some((animation) => document.querySelector('#opening-diagram').contains(animation.effect.target)));
  await page.screenshot({ path: `${output}/${phase}-mobile.png` });
  await page.locator('.guide-rail a[href="#delays"]').click();
  assert.equal(await page.locator('#delays').evaluate((el) => document.activeElement === el), true);
  await page.waitForFunction(() => document.querySelector('.guide-rail a[href="#delays"]').getAttribute('aria-current') === 'location');
  await page.locator('#delay').focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#delay').inputValue(), '1');
  await page.locator('#delays').screenshot({ path: `${output}/${phase}-mobile-delay.png` });
  await page.locator('#field-sheet').scrollIntoViewIfNeeded();
  await page.screenshot({ path: `${output}/${phase}-mobile-sheet.png` });

  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.locator('#diagram-replay').click();
  assert.equal(await page.locator('#opening-diagram').getAttribute('data-stage'), '3');
  assert.equal(await page.locator('.diagram-loop').evaluate((el) => getComputedStyle(el).opacity), '1');
  const blocked = await browser.newContext();
  await blocked.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('blocked'); } }));
  const blockedPage = await blocked.newPage();
  await blockedPage.goto(base);
  await blockedPage.locator('#pattern').fill('A note without storage.');
  await blockedPage.waitForFunction(() => document.querySelector('#sheet-status').textContent.includes('Available for this visit'));
  assert.equal(await blockedPage.locator('#pattern').inputValue(), 'A note without storage.');
  await blocked.close();
  const noJS = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
  const staticPage = await noJS.newPage();
  await staticPage.goto(base);
  assert.equal(await staticPage.locator('.lesson').count(), 7);
  assert.equal(await staticPage.locator('textarea:visible').count(), 4);
  await staticPage.locator('.ladder-row').first().locator('summary').click();
  assert.equal(await staticPage.locator('.ladder-row').first().getAttribute('open'), '');
  await staticPage.locator('.trap-card').first().locator('summary').click();
  assert.equal(await staticPage.locator('.trap-card').first().getAttribute('open'), '');
  await staticPage.screenshot({ path: `${output}/${phase}-nojs.png` });
  await noJS.close();
  const fonts = await page.evaluate(() => ({ serif: document.fonts.check('16px Newsreader'), sans: document.fonts.check('16px "Public Sans"') }));
  assert.deepEqual(fonts, { serif: true, sans: true });
  assert.ok(requests.every((url) => new URL(url).origin === new URL(base).origin), 'No runtime remote requests');
  assert.deepEqual(errors, []);
  console.log(`PASS ${phase}: model controls, spring replay, reduced motion, worksheet persistence/export, blocked storage, no-JS disclosures, keyboard input, print/restore, local fonts/assets, seven viewport widths; no page errors.`);
} finally { await browser.close(); }
