// Canonical practice names identify the book's chapters. Teaching copy, scenarios,
// and exercises below are original interpretations, not excerpts from the book.
export const practices = [
  {
    slug: 'its-all-invented', title: 'It’s All Invented', short: 'Question the frame',
    theme: 'perspective', time: 3,
    summary: 'Notice the assumptions shaping what you see. Try a frame with more room in it.',
    idea: 'Our interpretations shape the possibilities we notice.',
    explanation: 'The useful move is to distinguish an observation from the meaning you attach to it. An unanswered message is observable; “my idea is unwelcome” is an interpretation. You can take the observation seriously and still experiment with another explanation.',
    scenario: 'You suggest a change at work. Nobody responds in the meeting. By the afternoon, you have decided the idea was foolish.',
    oldFrame: 'Nobody spoke. They must think this is a bad idea.',
    newFrame: 'I have silence, not a verdict. What could I ask to learn more?',
    steps: ['Write one sentence describing what happened, using only what someone could have seen or heard.', 'Write the meaning you added. Begin with “I’m interpreting this as…”', 'Invent another plausible interpretation. Choose one question that would help you check it.'],
    prompt: 'What story am I treating as a fact, and what could I ask instead?',
    nuance: 'Changing a frame does not change a fact. Keep evidence, material limits, and other people’s experiences in view.',
    connection: 'The Way Things Are', related: 'the-way-things-are'
  },
  {
    slug: 'universe-of-possibility', title: 'Stepping into a Universe of Possibility', short: 'Open a different game',
    theme: 'perspective', time: 3,
    summary: 'Let comparison loosen its grip. Look for something worth creating together.',
    idea: 'A ranking is only one way to organize an experience.',
    explanation: 'When every conversation becomes a test of who is ahead, it is easy to miss curiosity, generosity, or an unexpected collaboration. Keep useful measures, but notice when they have become the entire purpose of your activity. Ask what you would make room for if your standing were not at stake.',
    scenario: 'A friend launches a project. You care about them, but your first response is to compare their progress with your own.',
    oldFrame: 'Their success means I am falling behind.',
    newFrame: 'Their work opens a conversation. What might we learn or make together?',
    steps: ['Name the comparison occupying your attention.', 'Set that comparison aside for the next ten minutes. Name something you are curious about.', 'Offer a question, introduction, or experiment that creates an opportunity for both of you.'],
    prompt: 'If I stopped keeping score for a moment, what would I want to create?',
    nuance: 'Budgets, deadlines, and fair evaluation still matter. The invitation is to stop treating measurement as the only source of meaning.',
    connection: 'Being a Contribution', related: 'being-a-contribution'
  },
  {
    slug: 'giving-an-a', title: 'Giving an A', short: 'Begin with possibility',
    theme: 'connection', time: 5,
    summary: 'Meet someone as a person capable of growth, before asking them to prove it.',
    idea: 'Begin a relationship by granting the other person room to develop.',
    explanation: 'An expectation of inadequacy can turn every exchange into a defense. Try approaching a learner, colleague, or yourself with a generous expectation of what could emerge. Then make the conditions for that growth specific: useful feedback, a chance to practice, and a clear next step.',
    scenario: 'A new teammate asks a basic question for the third time. You are about to label them as someone who cannot keep up.',
    oldFrame: 'They need to earn my confidence before I invest in them.',
    newFrame: 'I can assume capacity and help build the conditions for it to show.',
    steps: ['Pick a relationship where you have already written a limiting verdict.', 'Imagine a month of real development. Describe the habits and actions you would hope to see.', 'Name one thing you can do today to support that development. Ask the other person what would help.'],
    prompt: 'Who could I meet with more generosity, and how would my next conversation change?',
    nuance: 'Generosity is compatible with honest feedback and boundaries. It does not require pretending work meets a standard when it does not.',
    connection: 'Leading from Any Chair', related: 'leading-from-any-chair'
  },
  {
    slug: 'being-a-contribution', title: 'Being a Contribution', short: 'Bring what you can',
    theme: 'action', time: 2,
    summary: 'Trade the verdict on your worth for a useful offering in this moment.',
    idea: 'Make a contribution the point of your participation.',
    explanation: 'The question of whether you are impressive can swallow the attention you need to be useful. A contribution can be ordinary: asking a clear question, making space for a quieter voice, or sharing a tool. Its value does not depend on winning credit for it.',
    scenario: 'You join a community project full of experienced people and wonder whether you have anything important enough to offer.',
    oldFrame: 'I should wait until I have something exceptional to add.',
    newFrame: 'What is needed here that I can help with now?',
    steps: ['Look at the situation around you. Name one concrete need.', 'Choose a small offering that fits your capacity today.', 'Make the offering. Later, notice what it enabled without turning it into a rating of yourself.'],
    prompt: 'What is one useful thing I can offer today, without needing it to prove anything?',
    nuance: 'Contribution is a choice, not a demand for endless availability. Rest and a clear limit can help a group work more sustainably.',
    connection: 'Stepping into a Universe of Possibility', related: 'universe-of-possibility'
  },
  {
    slug: 'leading-from-any-chair', title: 'Leading from Any Chair', short: 'Lead from where you are',
    theme: 'connection', time: 4,
    summary: 'Influence the quality of the whole, whatever your title or place in the room.',
    idea: 'Leadership can come from any participant.',
    explanation: 'A title gives someone authority, but it does not give them all the insight. Pay attention to how your participation helps others contribute. If you hold formal power, invite specific feedback and show that it can change what you do. If you do not, look for a useful move within your reach.',
    scenario: 'A meeting keeps returning to the same disagreement. You are the newest person there, so you hesitate to interrupt.',
    oldFrame: 'It is not my meeting to improve.',
    newFrame: 'I can offer an observation that helps this group move.',
    steps: ['Notice one thing making participation harder for someone else.', 'Offer a specific, respectful intervention: a clarifying question, an invitation, or a summary.', 'If you are leading, ask what you could change to help the group do its best work. Act on one answer.'],
    prompt: 'What could I do from my current position to help someone else contribute?',
    nuance: 'Influence is not the same as authority. Respect responsibilities and recognize that speaking up carries different risks for different people.',
    connection: 'Giving an A', related: 'giving-an-a'
  },
  {
    slug: 'rule-number-six', title: 'Rule Number 6', short: 'Loosen your grip',
    theme: 'perspective', time: 2,
    summary: 'Take a breath. Your dignity can survive a small mistake or a changed mind.',
    idea: 'A lighter grip on self-importance creates room to respond.',
    explanation: 'When protecting your image becomes the main task, a small inconvenience can feel enormous. Notice the part of you that needs to look right, capable, or in control. A little kind humor can interrupt that performance and return your attention to the people and work in front of you.',
    scenario: 'You mispronounce a word during a presentation. You spend the next five minutes imagining everyone judging you.',
    oldFrame: 'I have ruined how they see me.',
    newFrame: 'A human made a small mistake. I can smile, correct it, and continue.',
    steps: ['Pause and release a little tension in your shoulders or jaw.', 'Name the image of yourself you are working so hard to protect.', 'Find a kind, slightly funny description of the moment. Then return to the useful next move.'],
    prompt: 'What becomes easier if I do not have to look perfect right now?',
    nuance: 'Humor should create space, not belittle someone or dismiss genuine harm. You can take a problem seriously while softening your self-defense.',
    connection: 'Giving Way to Passion', related: 'giving-way-to-passion'
  },
  {
    slug: 'the-way-things-are', title: 'The Way Things Are', short: 'Start with what is here',
    theme: 'perspective', time: 3,
    summary: 'Meet the actual situation, including your feelings, and choose a next step.',
    idea: 'Contact with reality is the starting place for a useful response.',
    explanation: 'You can spend a lot of energy arguing internally with something that has already happened. Acknowledge the circumstances and your feelings about them. From there, distinguish what is fixed for now from what remains open to action.',
    scenario: 'An outdoor event is canceled by a storm. You have spent weeks planning it and feel disappointed and angry.',
    oldFrame: 'This should not be happening. Everything is wasted.',
    newFrame: 'The event cannot happen outside. I am disappointed. What can we still offer?',
    steps: ['Describe the present circumstances without adding what should have happened.', 'Name your feeling without trying to remove or justify it.', 'Identify one available action. It can be rescheduling, asking for help, or taking a needed pause.'],
    prompt: 'What is true right now, and what is still available to me?',
    nuance: 'Acknowledging a situation does not mean approving it. You can recognize an injustice clearly and work to change it.',
    connection: 'It’s All Invented', related: 'its-all-invented'
  },
  {
    slug: 'giving-way-to-passion', title: 'Giving Way to Passion', short: 'Participate more fully',
    theme: 'action', time: 3,
    summary: 'Notice where self-consciousness holds you back. Bring more of yourself to the moment.',
    idea: 'Let yourself be moved by what you are doing.',
    explanation: 'Constantly watching yourself from the outside can keep you at a distance from an activity you care about. Try shifting attention toward the phrase you are playing, the idea you are sharing, or the person you are listening to. Let your body and attention participate as well as your analysis.',
    scenario: 'You love a subject, but present it in a careful monotone because you do not want your enthusiasm to seem excessive.',
    oldFrame: 'If I show how much I care, I might look foolish.',
    newFrame: 'My interest can help other people find a way into this.',
    steps: ['Choose a safe, small activity that matters to you.', 'Notice where you are bracing, holding your breath, or monitoring your appearance.', 'Try it again with fuller attention: a more expressive voice, an unhurried gesture, or closer listening.'],
    prompt: 'Where could I replace a little self-monitoring with fuller participation?',
    nuance: 'Full participation has many forms. Quiet attention counts; intensity, extroversion, and physical movement are not requirements.',
    connection: 'Rule Number 6', related: 'rule-number-six'
  },
  {
    slug: 'lighting-a-spark', title: 'Lighting a Spark', short: 'Offer an invitation',
    theme: 'connection', time: 4,
    summary: 'Share a possibility in a way that leaves others free to make it their own.',
    idea: 'Invite people into a possibility that matters to them too.',
    explanation: 'An invitation works differently from a campaign to overcome someone’s resistance. Share what you see and why you care. Listen for the other person’s interest, let their ideas change the proposal, and leave space for a genuine choice.',
    scenario: 'You want neighbors to create a shared garden. You have been explaining why everyone should volunteer, with little response.',
    oldFrame: 'How do I get them to agree to my plan?',
    newFrame: 'What could we grow here that they would want to be part of?',
    steps: ['Describe the possibility in one concrete sentence, without a sales pitch.', 'Ask the other person what would make the idea meaningful or useful to them.', 'Offer a small first step, with an easy way to decline or suggest something different.'],
    prompt: 'What invitation could I make that another person is free to reshape?',
    nuance: 'A respectful invitation includes the possibility of “no.” Enthusiasm does not replace consent, honest information, or mutual benefit.',
    connection: 'Telling the WE Story', related: 'telling-the-we-story'
  },
  {
    slug: 'being-the-board', title: 'Being the Board', short: 'Widen your responsibility',
    theme: 'action', time: 4,
    summary: 'Look beyond who is at fault to the conditions you can help change.',
    idea: 'Expand the context in which you can act.',
    explanation: 'When a situation looks like a contest between your move and someone else’s, your options may feel narrow. Step back and consider the arrangements, expectations, and conversations around the problem. Look for conditions you can influence without claiming that everything is your fault.',
    scenario: 'A collaborator misses a handoff again. You replay their failure, but the next deadline is already approaching.',
    oldFrame: 'Nothing can improve until they become more reliable.',
    newFrame: 'What agreement or earlier signal could make the next handoff work better?',
    steps: ['Describe the recurring difficulty and its impact.', 'Sketch the surrounding conditions: ownership, information, timing, and assumptions.', 'Choose one condition you can help change. Propose that change while keeping accountability clear.'],
    prompt: 'What condition around this problem could I help change?',
    nuance: 'Responsibility here is a stance toward available action, not blame for harm done to you. Safety, boundaries, and other people’s accountability remain essential.',
    connection: 'Creating Frameworks for Possibility', related: 'frameworks-for-possibility'
  },
  {
    slug: 'frameworks-for-possibility', title: 'Creating Frameworks for Possibility', short: 'Build a generous frame',
    theme: 'action', time: 5,
    summary: 'Turn a shared possibility into everyday agreements that keep it alive.',
    idea: 'Create a shared context that helps possibility persist.',
    explanation: 'A generous intention needs a form people can use. Make the possibility clear, behave in a way that embodies it, and establish ways to return to it when the group drifts. A useful frame guides decisions in a difficult moment as well as an inspiring one.',
    scenario: 'Your team says it values learning, but people hide unfinished work because reviews feel like public verdicts.',
    oldFrame: 'We need a more inspiring statement about creativity.',
    newFrame: 'What review practice would make sharing unfinished work easier?',
    steps: ['Name the possibility you want a group to experience.', 'Create one repeatable agreement that supports it: for example, begin reviews with questions before judgments.', 'Decide how to notice a drift and return to the agreement. Try it at the next gathering.'],
    prompt: 'What small, repeatable agreement would make our stated intention real?',
    nuance: 'A vision needs room for people to participate in shaping it. An inspiring phrase by itself does not change incentives or habits.',
    connection: 'Leading from Any Chair', related: 'leading-from-any-chair'
  },
  {
    slug: 'telling-the-we-story', title: 'Telling the WE Story', short: 'Find the larger “we”',
    theme: 'connection', time: 5,
    summary: 'Listen for the relationship and future that a story of opposing sides leaves out.',
    idea: 'Describe a shared situation in terms of connection and mutual possibility.',
    explanation: 'An account of my victory and your defeat leaves little space for a relationship to grow. Listen for what people care about, including the differences between them. Then try describing a future they could participate in creating together, without making one voice stand for everyone.',
    scenario: 'Two housemates argue about noise. One feels controlled; the other feels ignored. Each has a convincing story about the other’s selfishness.',
    oldFrame: 'Either I get my freedom or you get your peace.',
    newFrame: 'We are trying to make a home where rest and a social life both have room.',
    steps: ['Describe each person’s concern in words they could recognize. Ask rather than assume.', 'Name a shared situation or future that includes those concerns.', 'Invite everyone to revise the account and suggest one next experiment together.'],
    prompt: 'What shared future could include our differences without erasing them?',
    nuance: '“We” should not conceal unequal power or force agreement. Some needs require boundaries, repair, or a decision to separate.',
    connection: 'Lighting a Spark', related: 'lighting-a-spark'
  }
].map((practice, index) => ({ number: index + 1, ...practice }));

export const sources = [
  { title: 'The book, from Benjamin Zander', url: 'https://www.benjaminzander.org/the-art-of-possibility/', note: 'The authors’ collaboration and the book’s central invitation.' },
  { title: 'Published table of contents', url: 'https://books.google.com/books/about/The_Art_of_Possibility.html?id=AIdaBAAAQBAJ', note: 'Practice names, ordering, and publication information via Google Books.' },
  { title: 'Possibility in Action', url: 'https://www.benjaminzander.org/collection/possibility-in-action/', note: 'Public conversations and talks exploring the ideas with the authors.' },
  { title: 'A reader’s review of the twelve practices', url: 'https://thecreativemission.com/2021/01/26/book-review-the-art-of-possibility/', note: 'A secondary cross-check of the broad themes, by The Creative Mission.' }
];
