// Canonical practice names identify the book's chapters. Teaching copy, scenarios,
// and exercises below are original interpretations, not excerpts from the book.
export const practices = [
  {
    slug: 'its-all-invented', title: 'It’s All Invented', short: 'Question the frame',
    theme: 'perspective', time: 3,
    summary: "Separate the event from your interpretation. Test a different account.",
    idea: "What happened and what it means are two different things.",
    explanation: "You send a message and get no reply. That is an observation. Deciding that someone dislikes your idea adds a story to it. The story may be right, but you have not checked it yet. Notice which assumptions make your options seem fixed. Try another account, then ask a question that can give you evidence.",
    scenario: 'You suggest a change at work. Nobody responds in the meeting. By the afternoon, you have decided the idea was foolish.',
    oldFrame: 'Nobody spoke. They must think this is a bad idea.',
    newFrame: 'I have silence, not a verdict. What could I ask to learn more?',
    steps: ["Pick a recent moment that bothered you. Write what a camera could have recorded: who said or did what.", "On a second line, write the meaning you added. Start with: I am assuming that…", "Write one other plausible account. Choose a question you can ask to check which account fits."],
    outcome: "A question that tests an assumption, instead of acting on it as a fact.",
    prompt: "What am I assuming? Who could I ask, and what exactly will I ask them?",
    nuance: 'Changing a frame does not change a fact. Keep evidence, material limits, and other people’s experiences in view.',
    connection: 'The Way Things Are', related: 'the-way-things-are'
  },
  {
    slug: 'universe-of-possibility', title: 'Stepping into a Universe of Possibility', short: 'Open a different game',
    theme: 'perspective', time: 3,
    summary: "Set the ranking aside. Decide what you want to make or learn.",
    idea: "You can do more with a moment than measure your place in it.",
    explanation: "A conversation can become a contest over who knows more. A friend’s success can become evidence that you are behind. When you organize everything around your standing, you miss other uses for your attention. For a moment, set the score aside. Look for something to learn, make, or share. Useful measures can stay; they do not have to decide the whole purpose.",
    scenario: 'A friend launches a project. You care about them, but your first response is to compare their progress with your own.',
    oldFrame: 'Their success means I am falling behind.',
    newFrame: 'Their work opens a conversation. What might we learn or make together?',
    steps: ["Name the score you are keeping: praise, money, speed, status, or something else.", "Imagine that score is unavailable for ten minutes. Write one thing you would still want to make or learn.", "Take one step toward it: ask a question, share a draft, or invite someone to work with you."],
    outcome: "One action whose purpose is learning or creating, rather than improving your rank.",
    prompt: "What do I want to make or learn? What first step will I take today?",
    nuance: 'Budgets, deadlines, and fair evaluation still matter. The invitation is to stop treating measurement as the only source of meaning.',
    connection: 'Being a Contribution', related: 'being-a-contribution'
  },
  {
    slug: 'giving-an-a', title: 'Giving an A', short: 'Begin with possibility',
    theme: 'connection', time: 5,
    summary: "Replace a verdict on someone with a specific picture of their growth.",
    idea: "Treat a person as someone with capacity, before they have to defend their worth.",
    explanation: "Giving an A changes the starting point of a relationship. Instead of collecting proof that someone falls short, imagine what they could develop. Let that expectation change the way you listen and give feedback. You still name weak work clearly. The difference is that the work needs improvement; the person is not a fixed verdict. Try this with yourself as well as with someone else.",
    scenario: 'A new teammate asks a basic question for the third time. You are about to label them as someone who cannot keep up.',
    oldFrame: 'They need to earn my confidence before I invest in them.',
    newFrame: 'I can assume capacity and help build the conditions for it to show.',
    steps: ["Choose yourself or someone you are quick to judge. Name the verdict you have been carrying.", "Write a short note from a month in the future. Describe two actions that show how this person has developed. Keep it specific.", "Read the note as a possibility to support. Choose one thing you can change in your next conversation: a question, feedback, or a chance to try."],
    outcome: "A picture of development and one change in how you support it.",
    prompt: "What growth can I picture? What will I do differently in our next conversation?",
    nuance: 'Generosity is compatible with honest feedback and boundaries. It does not require pretending work meets a standard when it does not.',
    connection: 'Leading from Any Chair', related: 'leading-from-any-chair'
  },
  {
    slug: 'being-a-contribution', title: 'Being a Contribution', short: 'Bring what you can',
    theme: 'action', time: 2,
    summary: "Find one need you can help meet. Offer what you have.",
    idea: "You do not have to prove your worth before you can be useful.",
    explanation: "Am I impressive enough? That question draws attention toward your image. What can I contribute here? draws attention toward the situation. You might take notes, ask a clarifying question, or share something you know. Choose an offering within your capacity. Its purpose is to help, rather than settle whether you are a success or a failure.",
    scenario: 'You join a community project full of experienced people and wonder whether you have anything important enough to offer.',
    oldFrame: 'I should wait until I have something exceptional to add.',
    newFrame: 'What is needed here that I can help with now?',
    steps: ["Look at a group, task, or person you care about. Name one small unmet need.", "Choose something you can offer today. Make it small enough to do with the time and energy you have.", "Make the offer or do the task. Notice what it helps someone do, without giving yourself a score."],
    outcome: "One useful offering that fits your actual capacity.",
    prompt: "What will I offer, to whom, and when? Afterward, what did it help them do?",
    nuance: 'Contribution is a choice, not a demand for endless availability. Rest and a clear limit can help a group work more sustainably.',
    connection: 'Stepping into a Universe of Possibility', related: 'universe-of-possibility'
  },
  {
    slug: 'leading-from-any-chair', title: 'Leading from Any Chair', short: 'Lead from where you are',
    theme: 'connection', time: 4,
    summary: "Help the group do better work from the position you already hold.",
    idea: "You can help others contribute without being in charge.",
    explanation: "Notice what the whole group needs, rather than waiting for a title. A participant can summarize a confusing decision or ask for a voice that has been missed. A formal leader can ask for feedback and actually change the plan. The useful test is whether your participation helps others do their work. Authority and influence are different, and both affect what is possible.",
    scenario: 'A meeting keeps returning to the same disagreement. You are the newest person there, so you hesitate to interrupt.',
    oldFrame: 'It is not my meeting to improve.',
    newFrame: 'I can offer an observation that helps this group move.',
    steps: ["Think of your next meeting or shared task. Name one thing that would help someone else participate.", "Prepare one move within your role: summarize a decision, ask a question, or invite a missing perspective.", "Try it. If you are in charge, ask what you could change to help the group, and act on one answer."],
    outcome: "One move that helps the group use more of what its people know.",
    prompt: "What can I do from my current position? How will I know whether it helped?",
    nuance: 'Influence is not the same as authority. Respect responsibilities and recognize that speaking up carries different risks for different people.',
    connection: 'Giving an A', related: 'giving-an-a'
  },
  {
    slug: 'rule-number-six', title: 'Rule Number 6', short: 'Loosen your grip',
    theme: 'perspective', time: 2,
    summary: "Stop protecting a perfect image of yourself. Return to the work.",
    idea: "Take the task seriously. Hold your self-importance more lightly.",
    explanation: "A small mistake can become a crisis when you need everyone to see you as competent. Notice how much attention is going into defending that image. Let yourself be a person who can stumble, correct something, and keep participating. Kind humor can help. Aim it at your performance of perfection, rather than at someone else’s difficulty.",
    scenario: 'You mispronounce a word during a presentation. You spend the next five minutes imagining everyone judging you.',
    oldFrame: 'I have ruined how they see me.',
    newFrame: 'A human made a small mistake. I can smile, correct it, and continue.',
    steps: ["Pause. Let your shoulders or jaw soften. Name what has actually gone wrong.", "Name the image you are defending: always right, always capable, always in control.", "Give that demand a kind, mildly funny description. Then correct, apologize, or continue as the situation requires."],
    outcome: "A useful response with less energy spent protecting your image.",
    prompt: "What image am I defending? What can I do once I loosen that demand?",
    nuance: 'Humor should create space, not belittle someone or dismiss genuine harm. You can take a problem seriously while softening your self-defense.',
    connection: 'Giving Way to Passion', related: 'giving-way-to-passion'
  },
  {
    slug: 'the-way-things-are', title: 'The Way Things Are', short: 'Start with what is here',
    theme: 'perspective', time: 3,
    summary: "Name what is happening, including your feelings. Work from there.",
    idea: "You can respond more clearly when you stop arguing with what has already happened.",
    explanation: "An event is canceled. You are angry and disappointed. Both the cancellation and those feelings are part of the present situation. Name them without adding that the whole effort was worthless. Then ask what is still possible: another date, a smaller event, or a pause. Acknowledging reality gives you a place to act; it does not require liking it.",
    scenario: 'An outdoor event is canceled by a storm. You have spent weeks planning it and feel disappointed and angry.',
    oldFrame: 'This should not be happening. Everything is wasted.',
    newFrame: 'The event cannot happen outside. I am disappointed. What can we still offer?',
    steps: ["Write one sentence about what is happening now. Leave out what should have happened.", "Write one sentence about how you feel. You do not have to explain away the feeling.", "List two things still available to you. Choose one: ask for help, change the plan, act, or take a pause."],
    outcome: "An honest account of the present and one available next step.",
    prompt: "What is true now? What will I do from here, even if I do not like it?",
    nuance: 'Acknowledging a situation does not mean approving it. You can recognize an injustice clearly and work to change it.',
    connection: 'It’s All Invented', related: 'its-all-invented'
  },
  {
    slug: 'giving-way-to-passion', title: 'Giving Way to Passion', short: 'Participate more fully',
    theme: 'action', time: 3,
    summary: "Move your attention from how you look to what you care about.",
    idea: "Let the activity matter more than your performance of it.",
    explanation: "Self-monitoring puts you at a distance from what you are doing. You listen to your voice instead of the idea you want to share. You watch your playing instead of attending to the music. Try returning your attention to the activity itself. Let your voice, movement, or quiet concentration follow what matters in the moment. Start with a small, comfortable experiment.",
    scenario: 'You love a subject, but present it in a careful monotone because you do not want your enthusiasm to seem excessive.',
    oldFrame: 'If I show how much I care, I might look foolish.',
    newFrame: 'My interest can help other people find a way into this.',
    steps: ["Choose a small activity you care about: explaining an idea, playing a phrase, or listening to someone.", "Notice one way you are watching yourself instead of attending to the activity. Relax that effort a little.", "Try the activity again. Give your attention to the idea, sound, or person. Notice what changes in your voice, body, or listening."],
    outcome: "One experience of participating with less self-monitoring.",
    prompt: "What will I give my attention to? After trying it, what changed?",
    nuance: 'Full participation has many forms. Quiet attention counts; intensity, extroversion, and physical movement are not requirements.',
    connection: 'Rule Number 6', related: 'rule-number-six'
  },
  {
    slug: 'lighting-a-spark', title: 'Lighting a Spark', short: 'Offer an invitation',
    theme: 'connection', time: 4,
    summary: "Make an invitation someone else can help shape. Listen to their answer.",
    idea: "Share what you see as possible, then make room for another person’s interest.",
    explanation: "You cannot create shared enthusiasm by treating someone’s hesitation as an obstacle to defeat. Describe what you care about in concrete terms. Ask what would matter to them. Let their answer change the proposal. An invitation has room for a different idea and for a refusal. The aim is participation people choose, rather than agreement you extract.",
    scenario: 'You want neighbors to create a shared garden. You have been explaining why everyone should volunteer, with little response.',
    oldFrame: 'How do I get them to agree to my plan?',
    newFrame: 'What could we grow here that they would want to be part of?',
    steps: ["Describe something you want to create in one sentence. Include why you care about it.", "Ask someone what part, if any, interests them. Listen before proposing a role for them.", "Offer a small first step that fits their interest. Make it easy to decline or reshape the invitation."],
    outcome: "An invitation with room for the other person to change the proposal.",
    prompt: "Who will I invite? What will I ask before I suggest a first step?",
    nuance: 'A respectful invitation includes the possibility of “no.” Enthusiasm does not replace consent, honest information, or mutual benefit.',
    connection: 'Telling the WE Story', related: 'telling-the-we-story'
  },
  {
    slug: 'being-the-board', title: 'Being the Board', short: 'Widen your responsibility',
    theme: 'action', time: 4,
    summary: "Step back from the dispute. Change a condition that keeps it going.",
    idea: "Look at the whole setting in which a problem keeps happening.",
    explanation: "If you see yourself only as a piece reacting to someone else’s move, your next move may feel inevitable. The board metaphor asks you to widen the view. What agreements, information, and habits make this pattern possible? Consider where you can change the setting. This is a way to find agency, not a claim that you caused everything that happened to you.",
    scenario: 'A collaborator misses a handoff again. You replay their failure, but the next deadline is already approaching.',
    oldFrame: 'Nothing can improve until they become more reliable.',
    newFrame: 'What agreement or earlier signal could make the next handoff work better?',
    steps: ["Name a recurring problem and its impact. Keep the description specific.", "List the conditions around it: who knows what, who owns what, when signals arrive, and what is assumed.", "Circle one condition you can influence. Propose a concrete change, such as an earlier check-in or a clearer handoff."],
    outcome: "A change to the setting that could interrupt a recurring problem.",
    prompt: "Which condition can I help change? What proposal will I make?",
    nuance: 'Responsibility here is a stance toward available action, not blame for harm done to you. Safety, boundaries, and other people’s accountability remain essential.',
    connection: 'Creating Frameworks for Possibility', related: 'frameworks-for-possibility'
  },
  {
    slug: 'frameworks-for-possibility', title: 'Creating Frameworks for Possibility', short: 'Build a generous frame',
    theme: 'action', time: 5,
    summary: "Give a shared intention a repeatable form people can use.",
    idea: "A possibility lasts longer when everyday arrangements support it.",
    explanation: "We value learning is easy to say. A review where people can show unfinished work makes it usable. Name the kind of participation you want. Set up an agreement that supports it, model that agreement yourself, and decide how the group can return to it after a lapse. A frame should help people make choices when the work becomes difficult.",
    scenario: 'Your team says it values learning, but people hide unfinished work because reviews feel like public verdicts.',
    oldFrame: 'We need a more inspiring statement about creativity.',
    newFrame: 'What review practice would make sharing unfinished work easier?',
    steps: ["Name an intention your group shares, such as learning from unfinished work.", "Turn it into one repeatable agreement. For example: ask two questions about a draft before offering criticism.", "Propose trying the agreement once. Decide when you will review it and how anyone can point out a lapse."],
    outcome: "A repeatable agreement, a first trial, and a way to return to it.",
    prompt: "What agreement will we try? When will we review whether it helped?",
    nuance: 'A vision needs room for people to participate in shaping it. An inspiring phrase by itself does not change incentives or habits.',
    connection: 'Leading from Any Chair', related: 'leading-from-any-chair'
  },
  {
    slug: 'telling-the-we-story', title: 'Telling the WE Story', short: 'Find the larger “we”',
    theme: 'connection', time: 5,
    summary: "Describe a future that includes each person’s concern. Ask them to revise it.",
    idea: "Tell an account of the relationship, rather than only an account of opposing sides.",
    explanation: "My freedom versus your peace makes housemates into opponents. A home where both rest and friendship fit gives them something to design together. Start by listening to each person’s concern. Then name a shared situation and a future they could help create. Check the account with everyone involved. A useful we includes disagreement instead of speaking over it.",
    scenario: 'Two housemates argue about noise. One feels controlled; the other feels ignored. Each has a convincing story about the other’s selfishness.',
    oldFrame: 'Either I get my freedom or you get your peace.',
    newFrame: 'We are trying to make a home where rest and a social life both have room.',
    steps: ["Write each person’s concern in terms they would recognize. Ask them to correct your account.", "Write one sentence describing a shared future that has room for those concerns.", "Read it to the people involved. Invite revisions, then suggest one small experiment you can try together."],
    outcome: "A shared account people can revise, plus one experiment to try together.",
    prompt: "What future might include each of us? Who needs to help revise this account?",
    nuance: '“We” should not conceal unequal power or force agreement. Some needs require boundaries, repair, or a decision to separate.',
    connection: 'Lighting a Spark', related: 'lighting-a-spark'
  }
].map((practice, index) => ({ number: index + 1, ...practice }));

export const sources = [
  { title: 'The book, from Benjamin Zander', url: 'https://www.benjaminzander.org/the-art-of-possibility/', note: 'The authors’ collaboration and the book’s central invitation.' },
  { title: 'Published table of contents', url: 'https://books.google.com/books/about/The_Art_of_Possibility.html?id=AIdaBAAAQBAJ', note: 'Practice names, ordering, and publication information via Google Books.' },
  { title: 'Possibility in Action', url: 'https://www.benjaminzander.org/collection/possibility-in-action/', note: 'Public conversations and talks exploring the ideas with the authors.' },
];
